---
title: "WNV Data Import and Cleaning"
author: "Elisabeth Nelson"
date: "2022-09-20"
output: pdf_document
---

## Setting Libraries

```{r setup, include=FALSE}
library(dplyr)
library(readr)
pacman::p_load(
  lubridate,  # general package for handling and converting dates  
  linelist,   # has function to "guess" messy dates
  aweek,      # another option for converting dates to weeks, and weeks to dates
  zoo,        # additional date/time functions
  tidyverse,  # data management and visualization  
  rio, #importing data
  here, #relative file pathways
  janitor, #data cleaning and tables
  epikit) #ag_categories function
library(sf)
library(tigris)

```

## WNV Mosquito Data


```{r}
########### import and merge all CSV files into one data frame ###############

Cumulatve_Arbovirus_Survey_2001_to_2005 <- read.csv("~/Documents/Yale EMD/Rotation 1/WNV/Rotation-1-WNV/Data/Confidential/mozzie data/Cumulative Arbovirus Survey 2001 to 2005 .csv", sep = ",", header = TRUE)

Cumulative_Arbovirus_Survey_2006_to_2009 <- read.csv("~/Documents/Yale EMD/Rotation 1/WNV/Rotation-1-WNV/Data/Confidential/mozzie data/Cumulative Arbovirus Survey 2006 to 2009.csv", sep = ",", header = TRUE)

Cumulative_Arbovirus_Survey_2010_to_2012 <- read.csv("~/Documents/Yale EMD/Rotation 1/WNV/Rotation-1-WNV/Data/Confidential/mozzie data/Cumulative Arbovirus Survey 2010 to 2012.csv", sep = ",", header = TRUE)

Cumulative_Arbovirus_Survey_2013_to_2016 <- read.csv("~/Documents/Yale EMD/Rotation 1/WNV/Rotation-1-WNV/Data/Confidential/mozzie data/Cumulative Arbovirus Survey 2013 to 2016.csv", sep = ",", header = TRUE)

Cumulative_Arbovirus_Survey_2017_to_2019 <- read.csv("~/Documents/Yale EMD/Rotation 1/WNV/Rotation-1-WNV/Data/Confidential/mozzie data/Cumulative Arbovirus Survey 2017 to 2019.csv", sep = ",", header = TRUE)

Cumulative_Arbovirus_Survey_2020_to_2021 <- read.csv("~/Documents/Yale EMD/Rotation 1/WNV/Rotation-1-WNV/Data/Confidential/mozzie data/Cumulative Arbovirus Survey 2020 to 2021.csv", sep = ",", header = TRUE)

WNV_2001_to_2021_df <- rbind(Cumulatve_Arbovirus_Survey_2001_to_2005, 
                             Cumulative_Arbovirus_Survey_2006_to_2009, 
                             Cumulative_Arbovirus_Survey_2010_to_2012, 
                             Cumulative_Arbovirus_Survey_2013_to_2016,  
                             Cumulative_Arbovirus_Survey_2017_to_2019, 
                             Cumulative_Arbovirus_Survey_2020_to_2021)

#change the variable structure and makes species' names all lower case
WNV_2001_to_2021_df <- WNV_2001_to_2021_df %>%
  mutate(Species = tolower(Species)) %>%
  mutate(Species = as.factor(Species)) %>%
  mutate(Site = as.factor(Site)) %>%
  mutate(Town = as.factor(Town)) %>%
  mutate(County = as.factor(County)) %>%
  mutate(Trap.Type = as.factor(Trap.Type)) %>%
  mutate(Date = as.Date(Date, "%d-%b-%y")) %>%
  mutate(Virus = as.factor(Virus)) 

str(WNV_2001_to_2021_df)


#look at species' sums
species_table <- WNV_2001_to_2021_df %>%
  group_by(Species) %>%
  summarize(num_caught = sum(X..Mosquitoes)) 
species_table <- tibble(species_table)
species_table


#look at trap frequencies 
trap_table <- WNV_2001_to_2021_df %>%
  group_by(Site) %>%
  summarize(num_caught = sum(X..Mosquitoes))
trap_table

################# create df of only core traps #################

Coordinates_PRISM <- read_csv("Data/Confidential/Coordinates_PRISM.csv", 
    col_names = FALSE, col_types = cols(`41.44513` = col_number(), 
        `-72.99815` = col_number()))

core_traps_list <- Coordinates_PRISM$X3

core_traps <- WNV_2001_to_2021_df  %>%
  mutate(Site = as.character(Site)) %>%
  filter(Site %in% core_traps_list) %>%
  mutate(Site = as.factor(Site))

################# fix trap frequencies #################

core_traps_ff <- core_traps %>%
  arrange(Site, Species, Date) %>%
  group_by(Site,Species) %>%
  mutate(lag_date = lag(Date,1) ,
         sampleN=row_number(),
         sample_interval = as.numeric(Date - lag_date),
         sample_interval = if_else(sample_interval==0, 99,sample_interval)) %>%
  filter(sample_interval>=7)

```

## Land Cover Data
```{r}
############## Import trap geo-coordinate and land-cover data ##############
trap_location_land_cover <- read.csv("~/Documents/Yale EMD/Rotation 1/WNV/Rotation-1-WNV/Data/Confidential/CT Location with Habitat Description.csv", sep = ",", header = TRUE)
  
# change the formatting
trap_location_land_cover <- trap_location_land_cover %>%
  mutate(Location = as.factor(Location)) %>%
  mutate(City = as.factor(City)) %>%
  mutate(County = as.factor(County)) %>%
  mutate(Type.of.Collection.Site = as.factor(Type.of.Collection.Site)) 

############## group by type of land cover ##############
suburban_traps <- c("BB17", "BE74", "BF38", "BP39", "CR25", "CS96", "D41", "D42", "DB76", "E44", "EH43", "EL98", "FF31", "FF45", "G37", "GL77", "GR46", "GR47", "GR48", "GS99", "GU49", "HA78", "K27", "KL100", "MC80", "ME81", "MF51", "MF83", "MS102", "MV103", "N36", "NB55", "NC32", "NC53", "NEB84", "NG85",  "NO57", "NO58", "NS6", "NV56", "OR59", "RI34", "S2", "S94", "SA105", "SH60", "SO87", "ST64", "ST65", "SW86", "T16", "TR66", "WB90", "WE93", "WF20", "WG89", "WH104", "WK92", "WL14", "WN71", "WN72", "WO73", "WP69", "WP70", "WR91", "WT68")
rural_traps <- c("BH19", "BP40", "CA30", "CB93", "CC94", "CH23", "CL95", "CO29", "ED97", "FM18", "FR13", "H50", "HB107", "HD24", "HP97", "LD8", "LM28", "LY101", "	
LY21", "M26", "MI82", "MO52", "NS3", "NS5", "NS7", "OL22", "P10", "RE35", "S1", "SF15", "SP108", "SR109", "SS106", "TS110", "V9", "WD12", "WS111", "LY21")
urban_traps <- c("BP105", "NH54", "NH54 2019", "SM62", "SM63", "SM88") 
#length(suburban_traps) + length(rural_traps) + length(urban_traps)

 	


trap_location_land_cover <- trap_location_land_cover %>%
  mutate(updated_land_cover = case_when(
    Location %in% suburban_traps ~ "suburban", 
    Location %in% rural_traps ~ "rural", 
    Location %in% urban_traps ~ "urban"
  )) 
  
############## just trap locations ##############
trap_locations <- trap_location_land_cover %>%
  select(Location, Latitude, Longitude)



```

## Climate Data

```{r}
#### Import climate data from PRISM for trap locations 01/01/01-10/31/21 ####
Jan_2001_May_2001_PRISM_Climate_Data <- read_csv("Data/Confidential/Jan to May 2001 Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2001_May_2002_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2001 - May 2002 PRISM Climate Date.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2002_May_2003_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2002 - May 2003 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2003_May_2004_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2003 - May 2004 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2004_May_2005_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2004 - May 2005 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2005_May_2006_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2005 - May 2006 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2006_May_2007_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2006 - May 2007 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2007_May_2008_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2007 - May 2008 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2008_May_2009_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2008 - May 2009 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2009_May_2010_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2009 - May 2010 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2010_May_2011_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2010 - May 2011 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2011_May_2012_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2011 - May 2012 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2012_May_2013_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2013 - May 2012 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2013_May_2014_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2013 - May 2014 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2014_May_2015_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2014 - May 2015 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2015_May_2016_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2015 - May 2016 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2016_May_2017_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2016 - May 2017 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2017_May_2018_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2017 - May 2018  PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2018_May_2019_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2018 - May 2019 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2019_May_2020_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2019 - May 2020 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2020_May_2021_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2020 - May 2021 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))
June_2021_Nov_2021_PRISM_Climate_Data <- read_csv("Data/Confidential/June 2021 - Nov 2021 PRISM Climate Data.csv", 
    col_types = cols(Date = col_date(format = "%Y-%m-%d")))

trap_climate <- rbind(Jan_2001_May_2001_PRISM_Climate_Data, 
                      June_2001_May_2002_PRISM_Climate_Data, 
                      June_2002_May_2003_PRISM_Climate_Data, 
                      June_2003_May_2004_PRISM_Climate_Data, 
                      June_2004_May_2005_PRISM_Climate_Data, 
                      June_2005_May_2006_PRISM_Climate_Data, 
                      June_2006_May_2007_PRISM_Climate_Data, 
                      June_2007_May_2008_PRISM_Climate_Data, 
                      June_2008_May_2009_PRISM_Climate_Data,
                      June_2009_May_2010_PRISM_Climate_Data, 
                      June_2010_May_2011_PRISM_Climate_Data, 
                      June_2011_May_2012_PRISM_Climate_Data, 
                      June_2012_May_2013_PRISM_Climate_Data, 
                      June_2013_May_2014_PRISM_Climate_Data, 
                      June_2014_May_2015_PRISM_Climate_Data, 
                      June_2015_May_2016_PRISM_Climate_Data, 
                      June_2016_May_2017_PRISM_Climate_Data,
                      June_2017_May_2018_PRISM_Climate_Data, 
                      June_2018_May_2019_PRISM_Climate_Data, 
                      June_2019_May_2020_PRISM_Climate_Data, 
                      June_2020_May_2021_PRISM_Climate_Data, 
                      June_2021_Nov_2021_PRISM_Climate_Data)

#format traps at categories + rename columns 
# ppt in inches, temps in degrees F
trap_climate <- trap_climate %>%
  mutate(Name = as.character(Name)) %>%
  rename("ppt" = "ppt (inches)", "tmin" = "tmin (degrees F)", "tmean" = "tmean (degrees F)", "tmax" = "tmax (degrees F)", "tdmean" = "tdmean (degrees F)") 

trap_climate_with_lag <- trap_climate %>%
  group_by(Name) %>%
  mutate("lag_2_tmean" = lag(tmean, 14)) %>%
  mutate("lag_4_tmean" = lag(tmean, 28)) %>%
  mutate("lag_6_tmean" = lag(tmean, 42)) %>%
  mutate("lag_8_tmean" = lag(tmean, 56))

```


## Combine Climate and Case Data and Land-Cover and Case Data
```{r}

core_traps_ff <- left_join(core_traps_ff, trap_climate_with_lag, by = c("Site" = "Name", "Date" = "Date"), na.rm = TRUE)
core_traps_ff <- left_join(core_traps_ff, trap_location_land_cover, by = c("Site" = "Location"))

# delete unnecessary columns
core_traps_ff <- core_traps_ff %>%
  dplyr::select(-c(Accession.., lag_date, sampleN, sample_interval, `Elevation (ft)`, Latitude.y, Longitude.y, Nearest.Address, City, State, County.y))

```


## Map CT
```{r}
CT <- st_read(dsn = '/Users/zoe/Documents/Yale EMD/Rotation 1/WNV/Rotation-1-WNV/Data/Connecticut_and_Vicinity_Town_Boundary_Set/CT_Vicinity_Town_Polygon.shp')
str(CT)
CT <- CT %>%
  dplyr::filter(STATE_COD == "CT")
CT1_a <- as(CT,'Spatial')
CT_2 <- fortify(CT1_a)
```

